name: "Deploy GitHub Pages"

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn

      - name: Build GitHub Pages
        run: yarn build

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
          publish_dir: ./public
